#!/bin/bash

set -e
set -x
cd "$(dirname "$0")"

date

templates_dir="/usr/local/bin/templates"
test_repo=/tmp/test-repo
last_build="$HOME/.last_build"

rm -rf $test_repo
cd ../../ # we're in repo root

# copy the repo over to a temp directory and switch to it
rsync -ax --exclude site-builder/target . $test_repo
cd $test_repo
token=$(cat ./.token)
git reset --hard
git checkout bot-publish
git fetch
git reset --hard origin/gh-pages

# run the binary
GH_TOKEN=$token site-builder --template-file-path="$templates_dir/index.html" --out-file-path="$test_repo/out/index.html"
tailwindcss --content "$test_repo/out/*.html" -c "$templates_dir/tailwind.config.js" -i "$templates_dir/tw.css" -o "$test_repo/out/style.css"

# new file generated by binary
new="$test_repo/out/index.html"

if cmp --silent "$last_build" "$new"; then
    echo "files are the same, no need to publish"
    echo -e "\n-------------------------------------------------------------------------------------------\n"
    exit 0
fi

echo "files differ, publishing"
publish_date=$(date)
git add "$test_repo/out/index.html" "$test_repo/out/style.css"
git commit -m "Bot publish: $publish_date"
git subtree push --prefix out origin gh-pages

cp "$new" "$last_build"

echo -e "\n-------------------------------------------------------------------------------------------\n"
