#!/bin/bash

set -e
set -x
cd "$(dirname "$0")"

templates_dir="/usr/local/bin/templates"
test_repo=/tmp/test-repo
last_build="$HOME/.last_build"
publish_from="bot-publish"
push_to="gh-pages"

rm -rf $test_repo
cd ../../ # we're in repo root
read -r -p "Waiting"

# copy the repo over to a temp directory and switch to it
rsync -ax --exclude site-builder/target . $test_repo
cd $test_repo
git reset --hard
git checkout bot-publish
read -r -p "Waiting"

# run the binary
site-builder --template-file-path="$templates_dir/index.html" --out-file-path="$test_repo/out/index.html"
read -r -p "Waiting"
tailwindcss --content "$test_repo/out/*.html" -c "$templates_dir/tailwind.config.js" -i "$templates_dir/tw.css" -o "$test_repo/out/style.css"
read -r -p "Waiting"

# new file generated by binary
new="$test_repo/out/index.html"

# if cmp --silent "$last_build" "$new"; then
#   echo "files are the same, no need to publish"
#   exit 0
# fi

echo "files differ, publishing"
publish_date=$(date)
git add "$test_repo/out/index.html" "$test_repo/out/style.css"
git commit -m "Bot publish: $publish_date"
git subtree push --prefix out origin gh-pages

cp "$new" "$last_build"
